### ISSUE TITLE
因钉钉使用多想使用钉钉推送

### ISSUE THREAD

**Issue by a1150189233** [Le0nsec/SecCrawler#14]
钉钉推送 之前是用token就可以
现在需要加签 作者看看可以帮忙搞下嘛，万分感谢。

**Comment by Le0nsec** [comment]
有空会添加

**Comment by Le0nsec** [comment]
刚看了下，没有要求必须加签，可以设置关键字为年份，比如下图
<img width="560" alt="image" src="https://user-images.githubusercontent.com/66706544/161180477-c63ee92c-5cbf-4e11-8cb0-c9a1a4082bd3.png">
