### ISSUE TITLE
增加订阅资源

### ISSUE THREAD

**Issue by firmianay** [Le0nsec/SecCrawler#15]
老哥牛逼

希望能增加hackerone，RSS地址：https://rss.ricterz.me/hacktivity
还有CVE：https://nvd.nist.gov/vuln/data-feeds

感谢！

**Comment by gh0stkey** [comment]
复议，建议增加：https://github.com/HACK-THE-WORLD/DailyMorningReading

**Comment by firmianay** [comment]
自己动手丰衣足食：）
https://github.com/firmianay/yarb

**Comment by gh0stkey** [comment]
赞
