### ISSUE TITLE
建议添加接口

### ISSUE THREAD

**Issue by gh0stkey** [Le0nsec/SecCrawler#16]
建议添加接口，方便测试Webhook的连通性。

**Comment by Le0nsec** [comment]
没明白什么意思，是指单独一个接口去测webhook吗，可以直接使用`-test`测试

**Comment by gh0stkey** [comment]
不好意思，没看见`-test`，不过API控制爬虫时候好像不会自动Send to webhook

**Comment by Le0nsec** [comment]
了解了，后续会实现这个api

**Comment by gh0stkey** [comment]
好的，谢谢。
