### ISSUE TITLE
能否增加一个api接口，增强移植和可扩展性呢

### ISSUE THREAD

**Issue by komomon** [Le0nsec/SecCrawler#5]
能否增加一个api接口，增强移植和可扩展性呢，比如webapi

**Comment by komomon** [comment]
我对这个项目极感兴趣

**Comment by Le0nsec** [comment]
不错的建议，我有空会实现一下restful的api

komomon ***@***.***>于2022年1月28日 周五14:48写道：

**Comment by Le0nsec** [comment]
代码已经重构了一遍，增加了api模块，暂时增加了一个爬取文章的api
