### ISSUE TITLE
兼容自定义 推送API

### ISSUE THREAD

**Issue by keac** [Le0nsec/SecCrawler#9]
自己写了一个支持微信私聊/群聊推送的机器人，期待能够兼容接口或自定义推送接口方式

测试方法：微信搜索 WgpSecBot 添加后发送 【获取API】

## 推送格式 
```
https://bot.wgpsec.org/push/[key]?txt=xxx
```
![image](https://user-images.githubusercontent.com/16091665/155263061-d0cc6d26-8df8-43b0-bbdc-da53a099d8bb.png)

私聊
![image](https://user-images.githubusercontent.com/16091665/155262937-738bd74c-d402-432d-b268-e7235749843a.png)

微信群聊
![image](https://user-images.githubusercontent.com/16091665/155262845-8556e19b-3c2a-451d-afa4-083b6db14feb.png)

**Comment by Le0nsec** [comment]
感谢您的推荐，已完成
